---
- name: Install Docker
  hosts: your_target_hosts
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes